CREATE TABLE Images (
    image_id VARCHAR(40) NOT NULL PRIMARY KEY,
    url VARCHAR(100),
    Product VARCHAR(20),
    Pds_dataset_name VARCHAR(30),
    Pds_volume_name VARCHAR(20),
    Instrument_host VARCHAR(3),
    Instrument CHAR(4),
    Original_product VARCHAR(20),
    Product_version VARCHAR(5),
    Mission_phase_name VARCHAR(15),
    Rationale_desc VARCHAR(40),
    Data_quality INT,
    Nac_preroll_start_time DATE,
    Start_time DATE,
    Stop_time DATE,
    Spacecraft_clock_partition INT,
    Nac_spacecraft_clock_preroll_count VARCHAR(30),
    Spacecraft_clock_start_count VARCHAR(30),
    Spacecraft_clock_stop_count VARCHAR(30),
    Target_name VARCHAR(10),
    Orbit_number INT,
    Slew_angle DECIMAL(10,7),
    Lro_node_crossing VARCHAR(3),
    Lro_flight_direction VARCHAR(3),
    Nac_line_exposure_duration DECIMAL(10,7),
    Nac_frame VARCHAR(20),
    Nac_dac_reset INT,
    Nac_channel_a_offset INT,
    Nac_channel_b_offset INT,
    Instrument_mode_code INT,
    Compand_select_code INT,
    Mode_compression BOOL,
    Mode_test BOOL,
    Nac_temperature_scs DECIMAL(6,3),
    Nac_temperature_fpa DECIMAL(6,3),
    Nac_temperature_fpga DECIMAL(6,3),
    Nac_temperature_telescope DECIMAL(6,3),
    Image_lines INT,
    Line_samples INT,
    Sample_bits INT,
    Scaled_pixel_width DECIMAL(5,3),
    Scaled_pixel_height DECIMAL(5,3), 
    Resolution DECIMAL(10,9), 
    Emission_angle DECIMAL(5,2),
    Incidence_angle DECIMAL(5,2),
    Phase_angle DECIMAL(5,2),
    North_azimuth DECIMAL(5,2),
    Sub_solar_azimuth DECIMAL(5,2),
    Sub_solar_latitude DECIMAL(5,2),
    Sub_solar_longitude DECIMAL(5,2),
    Sub_spacecraft_latitude DECIMAL(5,2),
    Sub_spacecraft_longitude DECIMAL(5,2),
    Solar_distance DECIMAL(12,1),
    Solar_longitude DECIMAL(5,2),
    Center_latitude DECIMAL(5,2),
    Center_longitude DECIMAL(5,2),
    Upper_right_latitude DECIMAL(5,2),
    Upper_right_longitude DECIMAL(5,2),
    Lower_right_latitude DECIMAL(5,2),
    Lower_right_longitude DECIMAL(5,2),
    Lower_left_latitude DECIMAL(5,2),
    Lower_left_longitude DECIMAL(5,2),
    Upper_left_latitude DECIMAL(5,2),
    Upper_left_longitude DECIMAL(5,2),
    Spacecraft_altitude DECIMAL(7,3),
    Target_center_distance DECIMAL(6,2)
);

LOAD DATA INFILE '/var/lib/mysql-files/data.csv'
IGNORE INTO TABLE Images
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
(
  @image_id,
  @url,
  @product,
  @pds_dataset_name,
  @pds_volume_name,
  @instrument_host,
  @instrument,
  @original_product,
  @product_version,
  @mission_phase_name,
  @rationale_desc,
  @data_quality,
  @nac_preroll_start_time,
  @start_time,
  @stop_time,
  @spacecraft_clock_partition,
  @nac_spacecraft_clock_preroll_count,
  @spacecraft_clock_start_count,
  @spacecraft_clock_stop_count,
  @target_name,
  @orbit_number,
  @slew_angle,
  @lro_node_crossing,
  @lro_flight_direction,
  @nac_line_exposure_duration,
  @nac_frame,
  @nac_dac_reset,
  @nac_channel_a_offset,
  @nac_channel_b_offset,
  @instrument_mode_code,
  @compand_select_code,
  @mode_compression_str,
  @mode_test_str,
  @nac_temperature_scs,
  @nac_temperature_fpa,
  @nac_temperature_fpga,
  @nac_temperature_telescope,
  @image_lines,
  @line_samples,
  @sample_bits,
  @scaled_pixel_width_str,
  @scaled_pixel_height_str,
  @resolution,
  @emission_angle,
  @incidence_angle,
  @phase_angle,
  @north_azimuth,
  @sub_solar_azimuth,
  @sub_solar_latitude,
  @sub_solar_longitude,
  @sub_spacecraft_latitude,
  @sub_spacecraft_longitude,
  @solar_distance,
  @solar_longitude,
  @center_latitude,
  @center_longitude,
  @upper_right_latitude,
  @upper_right_longitude,
  @lower_right_latitude,
  @lower_right_longitude,
  @lower_left_latitude,
  @lower_left_longitude,
  @upper_left_latitude,
  @upper_left_longitude,
  @spacecraft_altitude,
  @target_center_distance
)
SET
  image_id = NULLIF(@image_id, 'NULL'),
  url                          = NULLIF(@url, 'NULL'),
  product                      = NULLIF(@product, 'NULL'),
  pds_dataset_name             = NULLIF(@pds_dataset_name, 'NULL'),
  pds_volume_name              = NULLIF(@pds_volume_name, 'NULL'),
  instrument_host              = NULLIF(@instrument_host, 'NULL'),
  instrument                   = NULLIF(@instrument, 'NULL'),
  original_product             = NULLIF(@original_product, 'NULL'),
  product_version              = NULLIF(@product_version, 'NULL'),
  mission_phase_name           = NULLIF(@mission_phase_name, 'NULL'),
  rationale_desc               = NULLIF(@rationale_desc, 'NULL'),
  data_quality                 = NULLIF(@data_quality, 'NULL'),         
  nac_preroll_start_time       = NULLIF(@nac_preroll_start_time, 'NULL'),
  start_time                   = NULLIF(@start_time, 'NULL'),
  stop_time                    = NULLIF(@stop_time, 'NULL'),
  spacecraft_clock_partition   = NULLIF(@spacecraft_clock_partition, 'NULL'),
  nac_spacecraft_clock_preroll_count   = NULLIF(@nac_spacecraft_clock_preroll_count, 'NULL'),
  spacecraft_clock_start_count = NULLIF(@spacecraft_clock_start_count, 'NULL'),
  spacecraft_clock_stop_count  = NULLIF(@spacecraft_clock_stop_count, 'NULL'),
  target_name                  = NULLIF(@target_name, 'NULL'),
  orbit_number                 = NULLIF(@orbit_number, 'NULL'),        
  slew_angle                   = NULLIF(@slew_angle, 'NULL'),          
  lro_node_crossing            = NULLIF(@lro_node_crossing, 'NULL'),   
  lro_flight_direction         = NULLIF(@lro_flight_direction, 'NULL'),
  nac_line_exposure_duration   = NULLIF(@nac_line_exposure_duration, 'NULL'),
  nac_frame                    = NULLIF(@nac_frame, 'NULL'),
  nac_dac_reset                = NULLIF(@nac_dac_reset, 'NULL'),
  nac_channel_a_offset         = NULLIF(@nac_channel_a_offset, 'NULL'),
  nac_channel_b_offset         = NULLIF(@nac_channel_b_offset, 'NULL'),
  instrument_mode_code         = NULLIF(@instrument_mode_code, 'NULL'),
  compand_select_code          = NULLIF(@compand_select_code, 'NULL'),
  mode_compression             = NULLIF(@mode_compression_str, 'NULL'),
  mode_test                    = NULLIF(@mode_test_str, 'NULL'),
  nac_temperature_scs          = NULLIF(@nac_temperature_scs, 'NULL'),
  nac_temperature_fpa          = NULLIF(@nac_temperature_fpa, 'NULL'),
  nac_temperature_fpga         = NULLIF(@nac_temperature_fpga, 'NULL'),
  nac_temperature_telescope    = NULLIF(@nac_temperature_telescope, 'NULL'),
  image_lines                  = NULLIF(@image_lines, 'NULL'),
  line_samples                 = NULLIF(@line_samples, 'NULL'),
  sample_bits                  = NULLIF(@sample_bits, 'NULL'),
  scaled_pixel_width           = NULLIF(@scaled_pixel_width_str, 'NULL'),
  scaled_pixel_height          = NULLIF(@scaled_pixel_height_str, 'NULL'),
  resolution                   = NULLIF(@resolution, 'NULL'),
  emission_angle               = NULLIF(@emission_angle, 'NULL'),
  incidence_angle              = NULLIF(@incidence_angle, 'NULL'),
  phase_angle                  = NULLIF(@phase_angle, 'NULL'),
  north_azimuth                = NULLIF(@north_azimuth, 'NULL'),
  sub_solar_azimuth            = NULLIF(@sub_solar_azimuth, 'NULL'),
  sub_solar_latitude           = NULLIF(@sub_solar_latitude, 'NULL'),
  sub_solar_longitude          = NULLIF(@sub_solar_longitude, 'NULL'),
  sub_spacecraft_latitude      = NULLIF(@sub_spacecraft_latitude, 'NULL'),
  sub_spacecraft_longitude     = NULLIF(@sub_spacecraft_longitude, 'NULL'),
  solar_distance               = NULLIF(@solar_distance, 'NULL'),
  solar_longitude              = NULLIF(@solar_longitude, 'NULL'),
  center_latitude              = NULLIF(@center_latitude, 'NULL'),
  center_longitude             = NULLIF(@center_longitude, 'NULL'),
  upper_right_latitude         = NULLIF(@upper_right_latitude, 'NULL'),
  upper_right_longitude        = NULLIF(@upper_right_longitude, 'NULL'),
  lower_right_latitude         = NULLIF(@lower_right_latitude, 'NULL'),
  lower_right_longitude        = NULLIF(@lower_right_longitude, 'NULL'),
  lower_left_latitude          = NULLIF(@lower_left_latitude, 'NULL'),
  lower_left_longitude         = NULLIF(@lower_left_longitude, 'NULL'),
  upper_left_latitude          = NULLIF(@upper_left_latitude, 'NULL'),
  upper_left_longitude         = NULLIF(@upper_left_longitude, 'NULL'),
  spacecraft_altitude          = NULLIF(@spacecraft_altitude, 'NULL'),
  target_center_distance       = NULLIF(@target_center_distance, 'NULL');

CREATE TABLE FeaturedImages (
    featured_image_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title varchar(40) NOT NULL,
    description TEXT NOT NULL,
    feature_date DATE NOT NULL,
    image_id VARCHAR(40) NOT NULL,
    FOREIGN KEY (image_id) REFERENCES Images(image_id)
);

CREATE TABLE BoundingBox (
    bounding_box_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    min_lat DOUBLE NOT NULL,
    min_long DOUBLE NOT NULL,
    max_lat DOUBLE NOT NULL,
    max_long DOUBLE NOT NULL
);

CREATE TABLE LandingSites (
    landing_site_name VARCHAR(40) NOT NULL PRIMARY KEY,
    description TEXT NOT NULL,
    mission VARCHAR(20) NOT NULL,
    bounding_box_id INT NOT NULL,
    FOREIGN KEY (bounding_box_id) REFERENCES BoundingBox(bounding_box_id)
);

